import os
#Countries
ARGENTINA = "ARG"
AUSTRIA = "AUT"
AUSTRALIA = "AUS"
BELGICA = "BEL"
BRASIL = "BRA"
CANADA = "CAN"
CHILE = "CHI"
CHINA = "CHN"
COLOMBIA = "COL"
CROACIA = "CRO"
EL_SALVADOR = "ESA"
FRANCIA = "FRA"
ALEMANIA = "GER"
HOLANDA = "NED"
HUNGRIA = "HUN"
IRLANDA = "IRL"
ITALIA = "ITA"
JAPON = "JPN"
KOREA = "KOR"
MEXICO = "MEX"
NUEVA_ZELANDA = "NZL"
NORUEGA = "NOR"
PANAMA = "PAN"
PARAGUAY = "PAR"
POLONIA = "POL"
PORTUGAL = "POR"
PUERTO_RICO = "PUR"
ESLOVAQUIA = "SVK"
SUDAFRICA = "RSA"
ESPANIA = "ESP"
SUIZA = "SUI"
TURQUIA = "TUR"
REINO_UNIDO = "GBR"
ESTADOS_UNIDOS = "USA"
REPUBLICA_CHECA = "CZE"

COUNTRIES = {ARGENTINA,AUSTRIA,AUSTRALIA,BELGICA,BRASIL,CANADA,CHILE,CHINA,COLOMBIA,CROACIA,EL_SALVADOR,FRANCIA,ALEMANIA,HOLANDA,HUNGRIA,IRLANDA,ITALIA,JAPON,KOREA,MEXICO,NUEVA_ZELANDA,NORUEGA,PANAMA,PARAGUAY,POLONIA,PORTUGAL,PUERTO_RICO,ESLOVAQUIA,SUDAFRICA,ESPANIA,SUIZA,TURQUIA,REINO_UNIDO,ESTADOS_UNIDOS,REPUBLICA_CHECA}



path_to_images = "../images/"

countries_images = {}
for country_name in COUNTRIES:
	countries_images.update({country_name:path_to_images+country_name.lower()})

