import os

#AUSTRIA = "AUT"
#COLOMBIA = "COL"
#CROACIA = "CRO"
#NUEVA_ZELANDA = "NZL"
#PANAMA = "PAN'
#PUERTO_RICO = "PUR"
#SUDAFRICA = "RSA"
#REPUBLICA_CHECA = "CZE"
#TURQUIA = 'TUR'

#Countries
ARGENTINA = "ARG"
AUSTRALIA = "AUS"
BELGICA = "BEL"
BRASIL = "BRA"
CANADA = "CAN"
CHILE = "CHI"
CHINA = "CHN"
EL_SALVADOR = "ESA"
FRANCIA = "FRA"
ALEMANIA = "GER"
HOLANDA = "NED"
HUNGRIA = "HUN"
IRLANDA = "IRL"
ITALIA = "ITA"
JAPON = "JPN"
KOREA = "KOR"
MEXICO = "MEX"
NORUEGA = "NOR"
PARAGUAY = "PAR"
PORTUGAL = "POR"
ESLOVAQUIA = "SVK"
ESPANIA = "ESP"
SUECIA = "SWE"
SUIZA = "SUI"
REINO_UNIDO = "GBR"
ESTADOS_UNIDOS = "USA"
NO_COUNTRY = "NCC"

COUNTRIES = {NO_COUNTRY,ARGENTINA,AUSTRALIA,BELGICA,BRASIL,CANADA,CHILE,CHINA,EL_SALVADOR,FRANCIA,ALEMANIA,HOLANDA,HUNGRIA,IRLANDA,ITALIA,JAPON,KOREA,MEXICO,NORUEGA,PARAGUAY,PORTUGAL,ESLOVAQUIA,ESPANIA,SUIZA,SUECIA,REINO_UNIDO,ESTADOS_UNIDOS}

path_to_images = "../images/"

countries_images = {}
for country_name in COUNTRIES:
	countries_images.update({country_name:path_to_images+country_name.lower()})




NAMES_FILE_PATH  =  '../input/names.txt'
DATE_FILE_PATH  =  '../input/dates.txt'
RESULT_FILE_PATH  =  '../output/result.txt'
JSON_FILE_PATH  =  '../output/table.json'
